# Generated by Django 4.0.6 on 2022-12-05 19:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_card_answer_alter_card_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='answer',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='question',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
